# Generated by Django 6.0.4 on 2026-05-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
