# Generated by Django 6.0.4 on 2026-05-16 17:51

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_publicpageshare_userpageshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=notes.models._attachment_upload_path),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notes.page",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
